// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// return_hdp_mc
List return_hdp_mc(NumericVector q, double Se, double Sp, int M);
RcppExport SEXP _genGT_return_hdp_mc(SEXP qSEXP, SEXP SeSEXP, SEXP SpSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type Se(SeSEXP);
    Rcpp::traits::input_parameter< double >::type Sp(SpSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(return_hdp_mc(q, Se, Sp, M));
    return rcpp_result_gen;
END_RCPP
}
// return_hdp
List return_hdp(NumericVector q, double Se, double Sp);
RcppExport SEXP _genGT_return_hdp(SEXP qSEXP, SEXP SeSEXP, SEXP SpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type Se(SeSEXP);
    Rcpp::traits::input_parameter< double >::type Sp(SpSEXP);
    rcpp_result_gen = Rcpp::wrap(return_hdp(q, Se, Sp));
    return rcpp_result_gen;
END_RCPP
}
// sim_screen
List sim_screen(NumericVector y, NumericVector q, double Se, double Sp, bool no_mc);
RcppExport SEXP _genGT_sim_screen(SEXP ySEXP, SEXP qSEXP, SEXP SeSEXP, SEXP SpSEXP, SEXP no_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type Se(SeSEXP);
    Rcpp::traits::input_parameter< double >::type Sp(SpSEXP);
    Rcpp::traits::input_parameter< bool >::type no_mc(no_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_screen(y, q, Se, Sp, no_mc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genGT_return_hdp_mc", (DL_FUNC) &_genGT_return_hdp_mc, 4},
    {"_genGT_return_hdp", (DL_FUNC) &_genGT_return_hdp, 3},
    {"_genGT_sim_screen", (DL_FUNC) &_genGT_sim_screen, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_genGT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
